import Mathlib.Data.Set.Lattice

/-!
# NF facets as complements of minimal transversals

This file proves the set-theoretic core of the NF operator.  A face of the
Stanley--Reisner complex of a facet family is precisely a subset which avoids
containing every member of that family.  The maximal such faces are exactly
the relative complements of the inclusion-minimal transversals.

The theorem is stated for an arbitrary family of subsets of an arbitrary
universe.  Finiteness, nonemptiness, and the antichain property are not needed.
In particular it applies to the facet family of a finite simplicial complex.
-/

namespace NFMinimalTransversal

universe u

variable {α : Type u}

/-- Every member of `C` is a subset of the ambient vertex set `V`. -/
def FamilyOn (V : Set α) (C : Set (Set α)) : Prop :=
  ∀ F ∈ C, F ⊆ V

/-- `S` contains no member of `C`.  These are the faces of the
Stanley--Reisner complex generated by the squarefree monomials indexed by
`C`. -/
def Avoids (C : Set (Set α)) (S : Set α) : Prop :=
  ∀ F ∈ C, ¬F ⊆ S

/-- A transversal (vertex cover) meets every member of `C`. -/
def IsTransversal (C : Set (Set α)) (T : Set α) : Prop :=
  ∀ F ∈ C, (F ∩ T).Nonempty

/-- An inclusion-maximal subset of `V` which avoids `C`. -/
def IsMaximalAvoider (V : Set α) (C : Set (Set α)) (S : Set α) : Prop :=
  S ⊆ V ∧ Avoids C S ∧
    ∀ U, S ⊆ U → U ⊆ V → Avoids C U → U = S

/-- An inclusion-minimal transversal contained in `V`. -/
def IsMinimalTransversal (V : Set α) (C : Set (Set α)) (T : Set α) : Prop :=
  T ⊆ V ∧ IsTransversal C T ∧
    ∀ U, U ⊆ T → IsTransversal C U → U = T

/-- The facet family of the avoiding complex generated by `C`. -/
def NFFacets (V : Set α) (C : Set (Set α)) : Set (Set α) :=
  {S | IsMaximalAvoider V C S}

/-- The family of inclusion-minimal transversals of `C` in `V`. -/
def minimalTransversals (V : Set α) (C : Set (Set α)) : Set (Set α) :=
  {T | IsMinimalTransversal V C T}

/-- Avoiding `C` is equivalent to the relative complement being a
transversal. -/
theorem avoids_iff_complement_transversal
    {V : Set α} {C : Set (Set α)} (hC : FamilyOn V C)
    {S : Set α} :
    Avoids C S ↔ IsTransversal C (V \ S) := by
  constructor
  · intro hAvoid F hF
    by_contra hEmpty
    apply hAvoid F hF
    intro x hxF
    by_contra hxS
    exact hEmpty ⟨x, hxF, hC F hF hxF, hxS⟩
  · intro hTrans F hF hFS
    obtain ⟨x, hxF, hxV, hxS⟩ := hTrans F hF
    exact hxS (hFS hxF)

/-- Relative complementation is involutive on subsets of `V`. -/
theorem diff_diff_of_subset {V S : Set α} (hS : S ⊆ V) :
    V \ (V \ S) = S := by
  ext x
  constructor
  · rintro ⟨hxV, hx⟩
    by_contra hxS
    exact hx ⟨hxV, hxS⟩
  · intro hxS
    exact ⟨hS hxS, fun hx => hx.2 hxS⟩

/-- Relative complementation exchanges maximal avoiding sets and minimal
transversals. -/
theorem maximalAvoider_iff_minimalTransversal_complement
    {V : Set α} {C : Set (Set α)} (hC : FamilyOn V C)
    {S : Set α} (hS : S ⊆ V) :
    IsMaximalAvoider V C S ↔ IsMinimalTransversal V C (V \ S) := by
  constructor
  · rintro ⟨-, hAvoid, hMax⟩
    refine ⟨Set.sdiff_subset, (avoids_iff_complement_transversal hC).1 hAvoid, ?_⟩
    intro T hT hTrans
    have hTV : T ⊆ V := hT.trans Set.sdiff_subset
    have hScomp : S ⊆ V \ T := by
      intro x hxS
      refine ⟨hS hxS, ?_⟩
      intro hxT
      exact (hT hxT).2 hxS
    have hAvoidComp : Avoids C (V \ T) := by
      rw [avoids_iff_complement_transversal hC,
        diff_diff_of_subset hTV]
      exact hTrans
    have hEq : V \ T = S := hMax (V \ T) hScomp Set.sdiff_subset hAvoidComp
    calc
      T = V \ (V \ T) := (diff_diff_of_subset hTV).symm
      _ = V \ S := by rw [hEq]
  · rintro ⟨hCompV, hTrans, hMin⟩
    have hAvoid : Avoids C S :=
      (avoids_iff_complement_transversal hC).2 hTrans
    refine ⟨hS, hAvoid, ?_⟩
    intro U hSU hUV hAvoidU
    have hDiffSub : V \ U ⊆ V \ S := Set.sdiff_subset_sdiff_right hSU
    have hTransDiff : IsTransversal C (V \ U) :=
      (avoids_iff_complement_transversal hC).1 hAvoidU
    have hEq : V \ U = V \ S := hMin (V \ U) hDiffSub hTransDiff
    calc
      U = V \ (V \ U) := (diff_diff_of_subset hUV).symm
      _ = V \ (V \ S) := by rw [hEq]
      _ = S := diff_diff_of_subset hS

/-- Exact blocker form of the NF-facet identity:

`NFFacets V C = {V \ T | T is a minimal transversal of C}`.

This is the combinatorial content of Equation (2) in Hibi--Mahmood, stripped
of the polynomial-ideal presentation. -/
theorem nfFacets_eq_complements_minimalTransversals
    {V : Set α} {C : Set (Set α)} (hC : FamilyOn V C) :
    NFFacets V C = (fun T => V \ T) '' minimalTransversals V C := by
  ext S
  constructor
  · intro hFacet
    have hS : S ⊆ V := hFacet.1
    exact ⟨V \ S,
      (maximalAvoider_iff_minimalTransversal_complement hC hS).1 hFacet,
      diff_diff_of_subset hS⟩
  · rintro ⟨T, hT, rfl⟩
    have hTV : T ⊆ V := hT.1
    apply (maximalAvoider_iff_minimalTransversal_complement hC Set.sdiff_subset).2
    rwa [diff_diff_of_subset hTV]

#print axioms avoids_iff_complement_transversal
#print axioms diff_diff_of_subset
#print axioms maximalAvoider_iff_minimalTransversal_complement
#print axioms nfFacets_eq_complements_minimalTransversals

end NFMinimalTransversal
