import AlbertsonDeletionColoring

#print axioms AlbertsonTutteBarrier.hasMatchingOff_iff
#print axioms AlbertsonTutteBarrier.oddComponents_ncard_eq_of_iso
#print axioms AlbertsonTutteBarrier.tutte_iff
#print axioms AlbertsonTutteBarrier.oddCount_delete
#print axioms AlbertsonTutteBarrier.ncard_union_image_remaining
#print axioms AlbertsonTutteBarrier.exists_oddCount_gap_two
#print axioms AlbertsonTutteBarrier.FactorCritical.oddCount_add_one_le
#print axioms AlbertsonTutteBarrier.FactorCritical.odd_card
#print axioms AlbertsonTutteBarrier.exists_deletion_witness
#print axioms AlbertsonTutteBarrier.exists_tight_witness_of_three_deleted

#check AlbertsonTutteBarrier.exists_deletion_witness
#check AlbertsonTutteBarrier.exists_tight_witness_of_three_deleted

#print axioms AlbertsonTutteBarrier.matching_toEdge_ne_of_compl_adj
#print axioms AlbertsonTutteBarrier.cliqueMatchingColoring
#print axioms AlbertsonTutteBarrier.matching_edge_fiber_ncard
#print axioms AlbertsonTutteBarrier.matching_verts_ncard
#print axioms AlbertsonTutteBarrier.colorable_compl_of_clique_matching
#print axioms AlbertsonTutteBarrier.no_matchingOff_triangle_of_not_colorable
#print axioms AlbertsonTutteBarrier.exists_tight_witness_of_triangle
#print axioms AlbertsonTutteBarrier.exists_tight_witness_of_chromaticNumber

#check AlbertsonTutteBarrier.colorable_compl_of_clique_matching
#check AlbertsonTutteBarrier.exists_tight_witness_of_triangle
#check AlbertsonTutteBarrier.exists_tight_witness_of_chromaticNumber

#print axioms AlbertsonTutteBarrier.sum_fiber_ncard
#print axioms AlbertsonTutteBarrier.fiber_ncard_eq_of_lower
#print axioms AlbertsonTutteBarrier.existsUnique_other_of_fiber_two
#print axioms AlbertsonTutteBarrier.perfectMatching_compl_of_pair_coloring
#print axioms AlbertsonTutteBarrier.perfectMatching_compl_of_large_classes
#print axioms AlbertsonTutteBarrier.matching_on_set_of_pair_coloring
#print axioms AlbertsonTutteBarrier.factorCritical_compl_of_deletion_colorings
#print axioms AlbertsonTutteBarrier.exists_tight_witness_of_deletion_colorings

#check AlbertsonTutteBarrier.HasLargeDeletionColorings
#check AlbertsonTutteBarrier.factorCritical_compl_of_deletion_colorings
#check AlbertsonTutteBarrier.exists_tight_witness_of_deletion_colorings
