import AlbertsonNeighborhoodObstruction

#print axioms AlbertsonNeighborhoodObstruction.foldHom
#print axioms AlbertsonNeighborhoodObstruction.chromaticNumber_delete_eq_of_neighborSet_subset
#print axioms AlbertsonNeighborhoodObstruction.not_neighborSet_subset_of_chromatic_drop
#print axioms AlbertsonNeighborhoodObstruction.neighborSet_subset_of_compl_domination
#print axioms AlbertsonNeighborhoodObstruction.exists_compl_neighbor_not_adjacent
#print axioms AlbertsonNeighborhoodObstruction.not_isClique_of_neighborSet_subset

#check AlbertsonNeighborhoodObstruction.exists_compl_neighbor_not_adjacent
#check AlbertsonNeighborhoodObstruction.not_isClique_of_neighborSet_subset
