import AlbertsonNeighborhoodObstruction
import AlbertsonReservoirCapacity

#print axioms AlbertsonNeighborhoodObstruction.foldHom
#print axioms AlbertsonNeighborhoodObstruction.chromaticNumber_delete_eq_of_neighborSet_subset
#print axioms AlbertsonNeighborhoodObstruction.not_neighborSet_subset_of_chromatic_drop
#print axioms AlbertsonNeighborhoodObstruction.neighborSet_subset_of_compl_domination
#print axioms AlbertsonNeighborhoodObstruction.exists_compl_neighbor_not_adjacent
#print axioms AlbertsonNeighborhoodObstruction.not_isClique_of_neighborSet_subset

#check AlbertsonNeighborhoodObstruction.exists_compl_neighbor_not_adjacent
#check AlbertsonNeighborhoodObstruction.not_isClique_of_neighborSet_subset

#print axioms AlbertsonNeighborhoodObstruction.extendDeletionColoring
#print axioms AlbertsonNeighborhoodObstruction.exists_neighbor_of_color
#print axioms AlbertsonNeighborhoodObstruction.exists_reservoir_same_color
#print axioms AlbertsonNeighborhoodObstruction.exists_reservoir_injection
#print axioms AlbertsonNeighborhoodObstruction.reservoir_card_bound
#print axioms AlbertsonNeighborhoodObstruction.not_common_neighbor_of_singleton_reservoir
#print axioms AlbertsonNeighborhoodObstruction.disjoint_clique_neighbors_of_singleton_reservoir
#print axioms AlbertsonNeighborhoodObstruction.disjoint_clique_neighbors_of_chromatic_drop

#check AlbertsonNeighborhoodObstruction.exists_reservoir_injection
#check AlbertsonNeighborhoodObstruction.reservoir_card_bound
#check AlbertsonNeighborhoodObstruction.disjoint_clique_neighbors_of_chromatic_drop
