"""Exact verifier for the cubic endpoint residue module and equality criterion."""

from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from functools import cache
from itertools import product as cartesian_product
from math import comb

Element = tuple[int, int]
QElement = tuple[Fraction, Fraction]
Series = tuple[Element, ...]
Pair = tuple[Series, Series]
Partition = tuple[int, ...]
Signature = tuple[int, int, int, int, int]

CUTOFF = 6
EQUALITY_CUTOFF = 11


def reduce_pair(a: int, b: int) -> Element:
    """Canonicalize a+b*zeta modulo (1-zeta)^3.

    The ideal lattice is generated by (-3,-6) and (6,3).  The returned
    coordinates satisfy 0 <= a < 3 and 0 <= b < 9.
    """

    a %= 9
    b %= 9
    residue = a % 3
    return residue, (b - 2 * (a - residue)) % 9


ZERO = reduce_pair(0, 0)
ONE = reduce_pair(1, 0)
ZETA = reduce_pair(0, 1)
PI = reduce_pair(1, -1)


def add(left: Element, right: Element) -> Element:
    return reduce_pair(left[0] + right[0], left[1] + right[1])


def neg(value: Element) -> Element:
    return reduce_pair(-value[0], -value[1])


def mul(left: Element, right: Element) -> Element:
    a, b = left
    c, d = right
    return reduce_pair(a * c - b * d, a * d + b * c - b * d)


def scale(value: Element, scalar: int) -> Element:
    return reduce_pair(scalar * value[0], scalar * value[1])


def ring_power(base: Element, exponent: int) -> Element:
    result = ONE
    while exponent:
        if exponent & 1:
            result = mul(result, base)
        base = mul(base, base)
        exponent //= 2
    return result


def pi_digits(value: Element) -> tuple[int, int, int]:
    """Return the unique digits value=c0+c1*pi+c2*pi^2, ci in F_3."""

    matches = [
        (c0, c1, c2)
        for c0, c1, c2 in cartesian_product(range(3), repeat=3)
        if reduce_pair(c0 + c1, -c1 - 3 * c2) == value
    ]
    if len(matches) != 1:
        raise AssertionError((value, matches))
    return matches[0]


def fraction_mod_nine(value: Fraction) -> int:
    if value.denominator % 3 == 0:
        raise ValueError(f"coordinate is not 3-integral: {value}")
    return value.numerator * pow(value.denominator, -1, 9) % 9


def reduce_qelement(value: QElement) -> Element:
    return reduce_pair(
        fraction_mod_nine(value[0]),
        fraction_mod_nine(value[1]),
    )


def qadd(left: QElement, right: QElement) -> QElement:
    return left[0] + right[0], left[1] + right[1]


def qneg(value: QElement) -> QElement:
    return -value[0], -value[1]


def qmul(left: QElement, right: QElement) -> QElement:
    a, b = left
    c, d = right
    return a * c - b * d, a * d + b * c - b * d


QZERO: QElement = (Fraction(0), Fraction(0))
QONE: QElement = (Fraction(1), Fraction(0))
QZETA: QElement = (Fraction(0), Fraction(1))
QPI: QElement = (Fraction(1), Fraction(-1))


def qscale(value: QElement, scalar: int | Fraction) -> QElement:
    return scalar * value[0], scalar * value[1]


def qinverse(value: QElement) -> QElement:
    a, b = value
    norm = a * a - a * b + b * b
    if not norm:
        raise ZeroDivisionError(value)
    return (a - b) / norm, -b / norm


def qpower(base: QElement, exponent: int) -> QElement:
    if exponent < 0:
        return qpower(qinverse(base), -exponent)
    result = QONE
    while exponent:
        if exponent & 1:
            result = qmul(result, base)
        base = qmul(base, base)
        exponent //= 2
    return result


def series_product(left: Series, right: Series, cutoff: int = CUTOFF) -> Series:
    result = [ZERO] * cutoff
    for i, a in enumerate(left[:cutoff]):
        for j, b in enumerate(right[: cutoff - i]):
            result[i + j] = add(result[i + j], mul(a, b))
    return tuple(result)


def series_inverse(denominator: Series, cutoff: int = CUTOFF) -> Series:
    if denominator[0] != ONE:
        raise ValueError("only unit-normalized series are used")
    result = [ONE] + [ZERO] * (cutoff - 1)
    for degree in range(1, cutoff):
        total = ZERO
        for index in range(1, min(degree, len(denominator) - 1) + 1):
            total = add(total, mul(denominator[index], result[degree - index]))
        result[degree] = neg(total)
    return tuple(result)


def series_power(base: Series, exponent: int, cutoff: int = CUTOFF) -> Series:
    if exponent < 0:
        return series_power(series_inverse(base, cutoff), -exponent, cutoff)
    result = (ONE,) + (ZERO,) * (cutoff - 1)
    while exponent:
        if exponent & 1:
            result = series_product(result, base, cutoff)
        base = series_product(base, base, cutoff)
        exponent //= 2
    return result


def pair_product(left: Pair, right: Pair) -> Pair:
    return (
        series_product(left[0], right[0]),
        series_product(left[1], right[1]),
    )


def pair_inverse(value: Pair) -> Pair:
    return series_inverse(value[0]), series_inverse(value[1])


def pair_power(base: Pair, exponent: int) -> Pair:
    return series_power(base[0], exponent), series_power(base[1], exponent)


IDENTITY_SERIES: Series = (ONE,) + (ZERO,) * (CUTOFF - 1)
IDENTITY_PAIR: Pair = (IDENTITY_SERIES, IDENTITY_SERIES)


def pad(values: list[Element], cutoff: int = CUTOFF) -> Series:
    return tuple((values + [ZERO] * cutoff)[:cutoff])


def one_denominator(weight: int) -> Series:
    if weight % 3 == 0:
        raise ValueError(weight)
    coefficients = [
        QONE,
        qscale(QPI, Fraction(-(weight - 1), 2)),
        qscale(qpower(QPI, 2), Fraction((weight - 1) * (weight - 2), 6)),
    ]
    return pad([reduce_qelement(value) for value in coefficients])


def root_denominator(weight: int) -> Series:
    if weight % 3 == 0:
        raise ValueError(weight)
    root_power = qpower(QZETA, weight)
    denominator_inverse = qinverse(qadd(QONE, qneg(root_power)))
    coefficients = [QONE]
    for degree in range(1, 4):
        coefficients.append(
            qmul(
                qscale(
                    qmul(root_power, qpower(QPI, degree)),
                    (-1) ** (degree + 1) * comb(weight, degree),
                ),
                denominator_inverse,
            )
        )
    return pad([reduce_qelement(value) for value in coefficients])


def divisible_denominator() -> Series:
    return pad([ONE, neg(PI), add(PI, neg(ONE))])


@cache
def residue_generator(residue: int) -> Pair:
    if residue not in (1, 2, 4, 5, 7, 8):
        raise ValueError(residue)
    return (
        series_inverse(root_denominator(residue)),
        series_inverse(one_denominator(residue)),
    )


@cache
def basis_generators() -> tuple[Pair, Pair, Pair, Pair]:
    g1 = residue_generator(1)
    h2 = pair_product(residue_generator(2), pair_inverse(g1))
    h4 = pair_product(residue_generator(4), pair_inverse(g1))
    inverse_v = series_inverse(divisible_denominator())
    g0 = (inverse_v, inverse_v)
    return g1, h2, h4, g0


RESIDUE_COORDINATES = {
    1: (0, 0),
    2: (1, 0),
    4: (0, 1),
    5: (1, 2),
    7: (0, 2),
    8: (1, 1),
}


def clipped_pole_order(order: int) -> int:
    if order < 1:
        raise ValueError("a positive pole order is required")
    return order if order <= 5 else 6 + (order - 6) % 9


def endpoint_signature(partition: Partition) -> Signature:
    q = sum(weight % 3 == 0 for weight in partition)
    if q == 0:
        raise ValueError("the primitive cubic wave is absent when q=0")
    counts = {residue: 0 for residue in RESIDUE_COORDINATES}
    for weight in partition:
        if weight % 3:
            counts[weight % 9] += 1
    e = sum(counts.values())
    b = (counts[2] + counts[5] + counts[8]) % 3
    c = (counts[4] + 2 * counts[5] + 2 * counts[7] + counts[8]) % 3
    return (
        e % 27,
        b,
        c,
        clipped_pole_order(q),
        clipped_pole_order(q + e + 1),
    )


def gamma_from_signature(signature: Signature) -> Pair:
    e, b, c, root_order, _ = signature
    g1, h2, h4, g0 = basis_generators()
    return pair_product(
        pair_power(g1, e + 1),
        pair_product(
            pair_power(h2, b),
            pair_product(pair_power(h4, c), pair_power(g0, root_order % 9)),
        ),
    )


def direct_gamma(partition: Partition) -> Pair:
    result = residue_generator(1)  # the extra weight from 1-t
    inverse_v = series_inverse(divisible_denominator())
    for weight in partition:
        if weight % 3 == 0:
            factor = (inverse_v, inverse_v)
        else:
            factor = (
                series_inverse(root_denominator(weight)),
                series_inverse(one_denominator(weight)),
            )
        result = pair_product(result, factor)
    return result


def falling(start: int, length: int) -> int:
    result = 1
    for offset in range(length):
        result *= start - offset
    return result


@cache
def binomial_correction(length: int, cutoff: int) -> Series:
    result = (ONE,) + (ZERO,) * (cutoff - 1)
    for shift in range(1, length + 1):
        factor = (ONE, scale(PI, shift)) if cutoff > 1 else (ONE,)
        result = series_product(result, factor, cutoff)
    return result


def transform(local: Series, pole_order: int) -> Series:
    result = [ZERO] * CUTOFF
    for degree, coefficient in enumerate(local[: min(CUTOFF, pole_order)]):
        scalar = falling(pole_order - 1, degree)
        correction = binomial_correction(pole_order - degree - 1, CUTOFF - degree)
        for extra, correction_coefficient in enumerate(correction):
            result[degree + extra] = add(
                result[degree + extra],
                scale(mul(coefficient, correction_coefficient), scalar),
            )
    return tuple(result)


def rational_pair(signature: Signature) -> tuple[Series, Series]:
    gamma = gamma_from_signature(signature)
    return transform(gamma[0], signature[3]), transform(gamma[1], signature[4])


def rational_jet(signature: Signature, cutoff: int = EQUALITY_CUTOFF) -> Series:
    numerator, denominator = rational_pair(signature)
    return series_product(numerator, series_inverse(denominator, cutoff), cutoff)


def equal_transforms(first: Signature, second: Signature) -> bool:
    first_numerator, first_denominator = rational_pair(first)
    second_numerator, second_denominator = rational_pair(second)
    return series_product(
        first_numerator, second_denominator, EQUALITY_CUTOFF
    ) == series_product(second_numerator, first_denominator, EQUALITY_CUTOFF)


def all_normal_forms() -> list[Pair]:
    g1, h2, h4, g0 = basis_generators()
    powers = [
        [pair_power(g1, exponent) for exponent in range(27)],
        [pair_power(h2, exponent) for exponent in range(3)],
        [pair_power(h4, exponent) for exponent in range(3)],
        [pair_power(g0, exponent) for exponent in range(9)],
    ]
    result = []
    for a, b, c, q in cartesian_product(range(27), range(3), range(3), range(9)):
        result.append(
            pair_product(
                powers[0][a],
                pair_product(powers[1][b], pair_product(powers[2][c], powers[3][q])),
            )
        )
    return result


def family() -> tuple[Partition, Partition]:
    left = (9, 7, 6, 4, 4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1)
    right = (11, 7, 6, 4, 4, 4, 4, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1)
    return left, right


def verify() -> dict[str, object]:
    ring = {reduce_pair(a, b) for a in range(9) for b in range(9)}
    if len(ring) != 27 or ring_power(PI, 3) != ZERO or scale(ONE, 9) != ZERO:
        raise AssertionError("incorrect cyclotomic quotient")

    weight_period_checks = 0
    for weight in range(1, 181):
        if weight % 3:
            direct = (
                series_inverse(root_denominator(weight)),
                series_inverse(one_denominator(weight)),
            )
            shifted = (
                series_inverse(root_denominator(weight + 9)),
                series_inverse(one_denominator(weight + 9)),
            )
            if direct != shifted:
                raise AssertionError((weight, direct, shifted))
            weight_period_checks += 1

    g1, h2, h4, g0 = basis_generators()
    for residue, (b, c) in RESIDUE_COORDINATES.items():
        expected = pair_product(g1, pair_product(pair_power(h2, b), pair_power(h4, c)))
        if residue_generator(residue) != expected:
            raise AssertionError((residue, residue_generator(residue), expected))
    order_checks = {
        "g1": pair_power(g1, 27) == IDENTITY_PAIR and pair_power(g1, 9) != IDENTITY_PAIR,
        "h2": pair_power(h2, 3) == IDENTITY_PAIR and h2 != IDENTITY_PAIR,
        "h4": pair_power(h4, 3) == IDENTITY_PAIR and h4 != IDENTITY_PAIR,
        "g0": pair_power(g0, 9) == IDENTITY_PAIR and pair_power(g0, 3) != IDENTITY_PAIR,
    }
    if not all(order_checks.values()):
        raise AssertionError(order_checks)

    normal_forms = all_normal_forms()
    if len(set(normal_forms)) != 2187:
        raise AssertionError("normal forms are not unique")

    one_projections = set()
    for b, c, q in cartesian_product(range(3), range(3), range(9)):
        state = pair_product(
            pair_power(h2, b), pair_product(pair_power(h4, c), pair_power(g0, q))
        )[1]
        one_projections.add(
            (
                pi_digits(state[1])[1],
                pi_digits(state[2])[0],
                pi_digits(state[2])[2],
                pi_digits(state[4])[2],
            )
        )
    root_projections = {
        (
            pi_digits(state[1])[0],
            pi_digits(state[1])[2],
            pi_digits(state[3])[2],
        )
        for exponent in range(27)
        for state in (pair_power(g1, exponent)[0],)
    }
    if len(one_projections) != 81 or len(root_projections) != 27:
        raise AssertionError((len(one_projections), len(root_projections)))

    transform_period_checks = 0
    for local_pair in normal_forms:
        for side in (0, 1):
            for pole_order in range(6, 15):
                if transform(local_pair[side], pole_order) != transform(
                    local_pair[side], pole_order + 9
                ):
                    raise AssertionError((side, pole_order, local_pair))
                transform_period_checks += 1

    high_classes: set[Series] = set()
    for e, b, c, q_residue in cartesian_product(range(27), range(3), range(3), range(9)):
        root_order = 6 + (q_residue - 6) % 9
        one_residue = (q_residue + e + 1) % 9
        one_order = 6 + (one_residue - 6) % 9
        signature = (e, b, c, root_order, one_order)
        high_classes.add(rational_jet(signature))
    if len(high_classes) != 386:
        raise AssertionError(len(high_classes))

    small_left = (6, 5, 1)
    small_right = (7, 3, 2)
    small_signature = endpoint_signature(small_left)
    if small_signature != endpoint_signature(small_right):
        raise AssertionError((small_signature, endpoint_signature(small_right)))
    if direct_gamma(small_left) != direct_gamma(small_right):
        raise AssertionError("the nonrectangular boundary pair did not compress")
    if not equal_transforms(small_signature, endpoint_signature(small_right)):
        raise AssertionError("the boundary transforms differ")
    left_weights = (1, *small_left)
    right_weights = (1, *small_right)
    boundary_moments = (
        len(left_weights),
        sum(left_weights),
        sum(weight * weight for weight in left_weights),
    )
    if boundary_moments != (
        len(right_weights),
        sum(right_weights),
        sum(weight * weight for weight in right_weights),
    ):
        raise AssertionError("the exact boundary moment identity failed")

    left, right = family()
    left_signature = endpoint_signature(left)
    right_signature = endpoint_signature(right)
    if left_signature[:4] != (14, 1, 1, 8):
        raise AssertionError(left_signature)
    if right_signature[:4] != (14, 1, 0, 6):
        raise AssertionError(right_signature)
    left_jet = rational_jet(left_signature, 14)
    right_jet = rational_jet(right_signature, 14)
    difference = tuple(add(a, neg(b)) for a, b in zip(left_jet, right_jet, strict=True))
    expected = (ZERO,) * 3 + (mul(PI, PI),) + (ZERO,) * 10
    if difference != expected:
        raise AssertionError(difference)

    report: dict[str, object] = {
        "theorem": "cubic endpoint residue-module classification",
        "ring_order": len(ring),
        "local_group_order": len(set(normal_forms)),
        "local_group_type": [27, 9, 3, 3],
        "coordinate_digit_checks": len(one_projections) + len(root_projections),
        "weight_period_checks": weight_period_checks,
        "transform_period_checks": transform_period_checks,
        "high_signature_count": 2187,
        "high_rational_classes": len(high_classes),
        "boundary_pair": [list(small_left), list(small_right)],
        "boundary_moments": list(boundary_moments),
        "height_2095_layer": "X^3",
    }
    canonical = json.dumps(report, sort_keys=True, separators=(",", ":"))
    report["sha256"] = hashlib.sha256(canonical.encode()).hexdigest()
    return report


def main() -> None:
    report = verify()
    print(
        "VERIFIED cubic residue module; "
        f"group=C27xC9xC3xC3; normal_forms={report['local_group_order']}; "
        f"transform_period_checks={report['transform_period_checks']}; "
        f"high_jet_classes={report['high_rational_classes']}; "
        f"sha256={report['sha256']}"
    )


if __name__ == "__main__":
    main()
