import Mathlib.Algebra.Group.Submonoid.Membership
import Mathlib.Combinatorics.Quiver.Path.Vertices

/-!
# Directed closed-walk lengths are generated by simple-cycle lengths

This file proves the generic loop-erasure bridge used when a finite transfer
graph has been exhaustively classified by its vertex-simple directed cycles.
It uses Mathlib's dependent `Quiver.Path` representation directly.
-/

namespace Quiver.Path

variable {V : Type*} [Quiver V]

/-- A positive closed directed path with no repeated vertex before its final
return to the starting vertex. -/
def IsVertexSimpleCycle {v : V} (p : Path v v) : Prop :=
  0 < p.length ∧ p.vertices.dropLast.Nodup

/-- A natural number occurring as the length of a vertex-simple directed
cycle in the quiver. -/
def IsVertexSimpleCycleLength (n : ℕ) : Prop :=
  ∃ (v : V) (p : Path v v), IsVertexSimpleCycle p ∧ p.length = n

/-- Loop erasure for a finite directed path.  The residual path has no
repeated vertices, and the erased loops have vertex-simple-cycle lengths whose
sum accounts exactly for the removed length. -/
theorem exists_nodup_path_and_simpleCycleLengths [DecidableEq V]
    {a b : V} (p : Path a b) :
    ∃ (q : Path a b) (lengths : List ℕ),
      q.vertices.Nodup ∧
      (∀ n ∈ lengths, IsVertexSimpleCycleLength (V := V) n) ∧
      p.length = q.length + lengths.sum := by
  induction p with
  | nil =>
      exact ⟨Path.nil, [], by simp, by simp, by simp⟩
  | @cons b c p e ih =>
      obtain ⟨q, lengths, hq, hcycles, hlength⟩ := ih
      by_cases hc : c ∈ q.vertices
      · obtain ⟨q₁, q₂, hqeq⟩ := q.exists_eq_comp_of_mem_vertices hc
        have hparts : (q₁.vertices.dropLast ++ q₂.vertices).Nodup := by
          simpa [hqeq] using hq
        have hq₂ : q₂.vertices.Nodup := List.Nodup.of_append_right hparts
        have hq₂_vertices : q₂.vertices = c :: q₂.vertices.tail := by
          calc
            q₂.vertices = q₂.vertices.head q₂.vertices_ne_nil :: q₂.vertices.tail :=
              (List.cons_head_tail q₂.vertices_ne_nil).symm
            _ = c :: q₂.vertices.tail := by
              rw [q₂.vertices_head_eq q₂.vertices_ne_nil]
        have hq₁_prefix : (q₁.vertices.dropLast ++ [c]).Nodup := by
          have hparts' :
              ((q₁.vertices.dropLast ++ [c]) ++ q₂.vertices.tail).Nodup := by
            have hlist_eq :
                q₁.vertices.dropLast ++ q₂.vertices =
                  (q₁.vertices.dropLast ++ [c]) ++ q₂.vertices.tail := by
              conv_lhs => rw [hq₂_vertices]
              rw [List.append_cons]
            exact hlist_eq ▸ hparts
          exact List.Nodup.of_append_left hparts'
        have hq₁ : q₁.vertices.Nodup := by
          simpa only [dropLast_append_end_eq] using hq₁_prefix
        have hcycle : IsVertexSimpleCycle (q₂.cons e) := by
          constructor
          · simp
          · simpa using hq₂
        refine ⟨q₁, (q₂.cons e).length :: lengths, hq₁, ?_, ?_⟩
        · intro n hn
          simp only [List.mem_cons] at hn
          rcases hn with rfl | hn
          · exact ⟨c, q₂.cons e, hcycle, rfl⟩
          · exact hcycles n hn
        · have hq_length := congrArg Path.length hqeq
          simp only [length_comp] at hq_length
          simp only [length_cons, List.sum_cons]
          omega
      · refine ⟨q.cons e, lengths, ?_, hcycles, ?_⟩
        · simpa only [vertices_cons] using
            (List.nodup_concat q.vertices c).2 ⟨hc, hq⟩
        · simp only [length_cons]
          omega

/-- A closed path whose full vertex list has no repetitions is necessarily
the empty path. -/
theorem length_eq_zero_of_closed_vertices_nodup {v : V} (p : Path v v)
    (h : p.vertices.Nodup) : p.length = 0 := by
  cases p with
  | nil => rfl
  | cons p e =>
      have hcons : (p.vertices.concat v).Nodup := by
        simpa only [vertices_cons] using h
      have hnot : v ∉ p.vertices := (List.nodup_concat p.vertices v).1 hcons |>.1
      exact (hnot p.start_mem_vertices).elim

/-- Every directed closed-walk length is a sum of vertex-simple directed
cycle lengths.  The empty closed path gives the empty sum. -/
theorem exists_simpleCycleLengths_sum_eq_length [DecidableEq V]
    {v : V} (p : Path v v) :
    ∃ lengths : List ℕ,
      (∀ n ∈ lengths, IsVertexSimpleCycleLength (V := V) n) ∧
      lengths.sum = p.length := by
  obtain ⟨q, lengths, hq, hcycles, hlength⟩ :=
    exists_nodup_path_and_simpleCycleLengths p
  refine ⟨lengths, hcycles, ?_⟩
  have hqzero := length_eq_zero_of_closed_vertices_nodup q hq
  omega

/-- If `S` contains every vertex-simple directed cycle length, then every
closed-walk length lies in the additive submonoid generated by `S`.  This is
the exact bridge needed after an exhaustive simple-cycle classification. -/
theorem closedPath_length_mem_addSubmonoid_closure [DecidableEq V]
    (S : Set ℕ)
    (hS : ∀ {v : V} (p : Path v v), IsVertexSimpleCycle p → p.length ∈ S)
    {v : V} (p : Path v v) :
    p.length ∈ AddSubmonoid.closure S := by
  obtain ⟨lengths, hcycles, hlength⟩ :=
    exists_simpleCycleLengths_sum_eq_length p
  have list_sum_mem :
      ∀ xs : List ℕ,
        (∀ n ∈ xs, IsVertexSimpleCycleLength (V := V) n) →
        xs.sum ∈ AddSubmonoid.closure S := by
    intro xs hxs
    induction xs with
    | nil => exact (AddSubmonoid.closure S).zero_mem
    | cons n xs ih =>
        have hn : IsVertexSimpleCycleLength (V := V) n := hxs n (by simp)
        have htail : ∀ m ∈ xs, IsVertexSimpleCycleLength (V := V) m := by
          intro m hm
          exact hxs m (by simp [hm])
        obtain ⟨v, cycle, hcycle, rfl⟩ := hn
        simpa using (AddSubmonoid.closure S).add_mem
          (AddSubmonoid.subset_closure (hS cycle hcycle)) (ih htail)
  rw [← hlength]
  exact list_sum_mem lengths hcycles

#print axioms exists_nodup_path_and_simpleCycleLengths
#print axioms length_eq_zero_of_closed_vertices_nodup
#print axioms exists_simpleCycleLengths_sum_eq_length
#print axioms closedPath_length_mem_addSubmonoid_closure

end Quiver.Path
