import DirectedCycleDecomposition
import SemigroupEndpoint

/-!
# From classified transfer cycles to packing-total cycle orders

This file composes the generic directed loop-erasure theorem with the four
simple-cycle lengths reported by the external packing-total transfer-graph
enumeration.  It does not import or certify that enumeration.
-/

namespace PackingTotalSemigroup

open Quiver
open Quiver.Path

/-- Zero belongs to the four-generator closed-walk semigroup. -/
theorem generated54_106_107_108_zero : Generated54_106_107_108 0 := by
  exact ⟨0, 0, 0, 0, by norm_num⟩

/-- The four-generator closed-walk semigroup is closed under addition. -/
theorem generated54_106_107_108_add {m n : ℕ}
    (hm : Generated54_106_107_108 m)
    (hn : Generated54_106_107_108 n) :
    Generated54_106_107_108 (m + n) := by
  obtain ⟨a, b, c, d, rfl⟩ := hm
  obtain ⟨a', b', c', d', rfl⟩ := hn
  exact ⟨a + a', b + b', c + c', d + d', by omega⟩

/-- Each of the four enumerated simple-cycle lengths belongs to the reported
closed-walk semigroup. -/
theorem generated54_106_107_108_of_eq_generator {n : ℕ}
    (h : n = 54 ∨ n = 106 ∨ n = 107 ∨ n = 108) :
    Generated54_106_107_108 n := by
  rcases h with rfl | rfl | rfl | rfl
  · exact ⟨1, 0, 0, 0, by norm_num⟩
  · exact ⟨0, 1, 0, 0, by norm_num⟩
  · exact ⟨0, 0, 1, 0, by norm_num⟩
  · exact ⟨0, 0, 0, 1, by norm_num⟩

/-- If every vertex-simple directed cycle has one of the four externally
enumerated lengths, then every directed closed-walk length belongs to the
four-generator semigroup. -/
theorem closedPath_length_generated54_106_107_108
    {V : Type*} [Quiver V] [DecidableEq V]
    (hSimpleCycles : ∀ {v : V} (cycle : Path v v),
      cycle.IsVertexSimpleCycle →
        cycle.length = 54 ∨ cycle.length = 106 ∨
          cycle.length = 107 ∨ cycle.length = 108)
    {v : V} (p : Path v v) :
    Generated54_106_107_108 p.length := by
  obtain ⟨lengths, hcycles, hlength⟩ :=
    p.exists_simpleCycleLengths_sum_eq_length
  have list_generated :
      ∀ xs : List ℕ,
        (∀ n ∈ xs, IsVertexSimpleCycleLength (V := V) n) →
        Generated54_106_107_108 xs.sum := by
    intro xs hxs
    induction xs with
    | nil => exact generated54_106_107_108_zero
    | cons n xs ih =>
        have hn : IsVertexSimpleCycleLength (V := V) n := hxs n (by simp)
        have htail : ∀ m ∈ xs, IsVertexSimpleCycleLength (V := V) m := by
          intro m hm
          exact hxs m (by simp [hm])
        obtain ⟨w, cycle, hcycle, rfl⟩ := hn
        exact generated54_106_107_108_add
          (generated54_106_107_108_of_eq_generator
            (hSimpleCycles cycle hcycle))
          (ih htail)
  rw [← hlength]
  exact list_generated lengths hcycles

/-- Under the same exhaustive simple-cycle classification, an even closed
walk of length `2*n` forces the packing-total cycle order `n` to lie in the
numerical semigroup generated by `27` and `53`. -/
theorem closedPath_halfLength_generated27_53
    {V : Type*} [Quiver V] [DecidableEq V]
    (hSimpleCycles : ∀ {v : V} (cycle : Path v v),
      cycle.IsVertexSimpleCycle →
        cycle.length = 54 ∨ cycle.length = 106 ∨
          cycle.length = 107 ∨ cycle.length = 108)
    {v : V} (p : Path v v) (n : ℕ) (hp : p.length = 2 * n) :
    Generated27_53 n := by
  rw [← generated54_106_107_108_double_iff]
  rw [← hp]
  exact closedPath_length_generated54_106_107_108 hSimpleCycles p

#print axioms generated54_106_107_108_zero
#print axioms generated54_106_107_108_add
#print axioms generated54_106_107_108_of_eq_generator
#print axioms closedPath_length_generated54_106_107_108
#print axioms closedPath_halfLength_generated27_53

end PackingTotalSemigroup
