import Mathlib

/-!
# The arithmetic endpoint in the packing-total cycle classification

This file isolates the numerical-semigroup step that converts the externally
enumerated closed-walk lengths `54`, `106`, `107`, and `108` into the cycle
orders generated by `27` and `53`.  No transfer graph or enumeration output is
imported.
-/

namespace PackingTotalSemigroup

/-- Membership in the numerical semigroup generated by `27` and `53`. -/
def Generated27_53 (n : ℕ) : Prop :=
  ∃ a b : ℕ, n = 27 * a + 53 * b

/-- Membership in the additive semigroup generated by the four closed-walk
lengths reported by the transfer-graph computation. -/
def Generated54_106_107_108 (length : ℕ) : Prop :=
  ∃ a b c d : ℕ,
    length = 54 * a + 106 * b + 107 * c + 108 * d

/-- The least nonnegative coefficient of `53` compatible with `n` modulo
`27`, using `53 ≡ -1 (mod 27)`. -/
def residueCoefficient (n : ℕ) : ℕ :=
  (27 - n % 27) % 27

/-- For an explicitly generated number, the canonical coefficient is the
coefficient of `53` reduced modulo `27`. -/
theorem residueCoefficient_generated (a b : ℕ) :
    residueCoefficient (27 * a + 53 * b) = b % 27 := by
  have hb : b % 27 < 27 := Nat.mod_lt _ (by omega)
  interval_cases hbr : b % 27 <;>
    norm_num [residueCoefficient, Nat.add_mod, Nat.mul_mod, hbr]

/-- Exact Apéry-style membership test for the semigroup generated by `27`
and `53`: its canonical residue representative must not exceed `n`. -/
theorem generated27_53_iff_residue_bound (n : ℕ) :
    Generated27_53 n ↔ 53 * residueCoefficient n ≤ n := by
  constructor
  · rintro ⟨a, b, rfl⟩
    rw [residueCoefficient_generated]
    have hb := Nat.mod_le b 27
    omega
  · intro h
    let b := residueCoefficient n
    refine ⟨(n - 53 * b) / 27, b, ?_⟩
    dsimp [b, residueCoefficient] at h ⊢
    omega

/-- An even length lies in the four-generator closed-walk semigroup exactly
when its half lies in the cycle-order semigroup generated by `27` and `53`. -/
theorem generated54_106_107_108_double_iff (n : ℕ) :
    Generated54_106_107_108 (2 * n) ↔ Generated27_53 n := by
  constructor
  · rintro ⟨a, b, c, d, h⟩
    have hcmod : c % 2 = 0 := by
      have hmod := congrArg (fun x : ℕ ↦ x % 2) h
      norm_num [Nat.add_mod, Nat.mul_mod] at hmod ⊢
      omega
    obtain ⟨e, rfl⟩ : ∃ e : ℕ, c = 2 * e :=
      Nat.dvd_iff_mod_eq_zero.mpr hcmod
    refine ⟨a + 2 * e + 2 * d, b + e, ?_⟩
    omega
  · rintro ⟨a, b, h⟩
    exact ⟨a, b, 0, 0, by omega⟩

/-- Every integer at least `1352` belongs to the semigroup generated by
`27` and `53`. -/
theorem generated27_53_of_ge {n : ℕ} (h : 1352 ≤ n) :
    Generated27_53 n := by
  rw [generated27_53_iff_residue_bound]
  simp only [residueCoefficient]
  omega

/-- `1351` is not generated by `27` and `53`. -/
theorem not_generated27_53_1351 : ¬ Generated27_53 1351 := by
  rw [generated27_53_iff_residue_bound]
  norm_num [residueCoefficient]

/-- The exceptional orders from `14` through the Frobenius number, expressed
through the executable residue criterion. -/
def exceptionalOrders : Finset ℕ :=
  (Finset.Icc 14 1351).filter fun n ↦ n < 53 * residueCoefficient n

/-- Membership in `exceptionalOrders` is exactly nonmembership in the
semigroup, with the advertised range restriction. -/
theorem mem_exceptionalOrders_iff {n : ℕ} :
    n ∈ exceptionalOrders ↔
      14 ≤ n ∧ n ≤ 1351 ∧ ¬ Generated27_53 n := by
  simp only [exceptionalOrders, Finset.mem_filter, Finset.mem_Icc]
  rw [generated27_53_iff_residue_bound]
  omega

set_option maxRecDepth 100000 in
/-- There are exactly `663` exceptional orders at least `14`.  This is a
closed kernel reduction over the proved residue criterion, not imported data. -/
theorem card_exceptionalOrders : exceptionalOrders.card = 663 := by
  decide

/-- The Frobenius number of the numerical semigroup generated by `27` and
`53` is `1351`. -/
theorem frobenius_27_53 :
    IsGreatest {n : ℕ | ¬ Generated27_53 n} 1351 := by
  refine ⟨not_generated27_53_1351, ?_⟩
  intro n hn
  by_contra h
  exact hn (generated27_53_of_ge (by omega))

#print axioms generated27_53_iff_residue_bound
#print axioms generated54_106_107_108_double_iff
#print axioms generated27_53_of_ge
#print axioms not_generated27_53_1351
#print axioms mem_exceptionalOrders_iff
#print axioms card_exceptionalOrders
#print axioms frobenius_27_53

end PackingTotalSemigroup
