#!/usr/bin/env python3

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


REPRESENTATIVES = "objective_eleven_rotation_representatives"
SIGNATURES = "objective_eleven_incidence_signatures_2_through_10"


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_json_sha256(value: Any) -> str:
    payload = json.dumps(
        value, ensure_ascii=True, separators=(",", ":"), sort_keys=True
    ).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def aligned_pair_sha256(
    representatives: list[list[int]], signatures: list[list[int]]
) -> str:
    digest = hashlib.sha256()
    for representative, signature in zip(
        representatives, signatures, strict=True
    ):
        digest.update(
            json.dumps(
                [representative, signature],
                ensure_ascii=True,
                separators=(",", ":"),
            ).encode("ascii")
        )
        digest.update(b"\n")
    return digest.hexdigest()


def state_word_key(representative: list[int]) -> tuple[int, ...]:
    words = [0] * 15
    for edge in representative:
        words[edge // 64] |= 1 << (edge % 64)
    return tuple(words)


def summarize(direct_path: Path, optimized_path: Path) -> dict[str, Any]:
    direct = json.loads(direct_path.read_text())
    optimized = json.loads(optimized_path.read_text())
    if set(direct) != set(optimized):
        raise ValueError("frontier certificate keys disagree")
    for key in direct:
        if key == "method":
            continue
        if direct[key] != optimized[key]:
            raise ValueError(f"frontier certificate mismatch at {key}")

    representatives = direct[REPRESENTATIVES]
    signatures = direct[SIGNATURES]
    if len(representatives) != len(signatures):
        raise ValueError("representative/signature alignment mismatch")
    if representatives != sorted(representatives, key=state_word_key):
        raise ValueError("representatives are not sorted")
    if len({tuple(item) for item in representatives}) != len(representatives):
        raise ValueError("duplicate representative")

    summary = {
        key: value
        for key, value in direct.items()
        if key not in {REPRESENTATIVES, SIGNATURES, "method"}
    }
    summary.update(
        {
            "complete_representative_array_retained_in_regenerable_full_output": True,
            "complete_aligned_signature_array_retained_in_regenerable_full_output": True,
            "independent_mathematical_fields_agree": True,
            "independent_representative_arrays_agree_entry_for_entry": True,
            "independent_signature_arrays_agree_entry_for_entry": True,
            "representative_array_sha256_canonical_json": canonical_json_sha256(
                representatives
            ),
            "signature_array_sha256_canonical_json": canonical_json_sha256(
                signatures
            ),
            "aligned_representative_signature_pairs_sha256_json_lines": aligned_pair_sha256(
                representatives, signatures
            ),
            "direct_full_output_sha256": file_sha256(direct_path),
            "optimized_full_output_sha256": file_sha256(optimized_path),
            "direct_method": direct["method"],
            "optimized_method": optimized["method"],
            "hash_encoding": (
                "Arrays use ASCII JSON with separators ',' and ':' and sorted "
                "object keys. The aligned-pair digest hashes one compact JSON "
                "[representative,signature] pair plus newline per sorted orbit."
            ),
            "scope_note": (
                "Compact digest certificate for the complete first objective-"
                "eleven frontier of the certified primary threshold-ten "
                "component; full arrays are deterministically regenerated by "
                "the two source programs."
            ),
        }
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("direct", type=Path)
    parser.add_argument("optimized", type=Path)
    args = parser.parse_args()
    print(json.dumps(summarize(args.direct, args.optimized), indent=2))


if __name__ == "__main__":
    main()
